# Generated by Django 4.1.7 on 2023-03-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.ForeignKey(blank=True, default=None, help_text='Food Review', null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food'),
        ),
    ]
